DROP TABLE MENU CASCADE CONSTRAINT PURGE;
DROP TABLE JENIS_MAKANAN CASCADE CONSTRAINT PURGE;
DROP TABLE KARYAWAN CASCADE CONSTRAINT PURGE;
DROP TABLE JABATAN CASCADE CONSTRAINT PURGE;
DROP TABLE ABSENSI CASCADE CONSTRAINT PURGE;
DROP TABLE TRANSAKSI CASCADE CONSTRAINT PURGE;
DROP TABLE D_TRANSAKSI CASCADE CONSTRAINT PURGE;
DROP TABLE PELANGGAN CASCADE CONSTRAINT PURGE;

create table jenis_makanan ( --sudah
	ID NUMBER PRIMARY KEY, 
	ID_MAKANAN VARCHAR2(5) NOT NULL,
	NAMA_JENIS VARCHAR(50) NOT NULL
);
create table menu( --sudah
	ID NUMBER PRIMARY KEY, 
	ID_JENIS_MAKANAN NUMBER REFERENCES JENIS_MAKANAN(ID),
	KODE_MENU VARCHAR2(5) NOT NULL, 
	NAMA_MENU VARCHAR2(255) NOT NULL, 
	STATUS NUMBER NOT NULL CHECK(STATUS = 0 OR STATUS = 1) ,
	HARGA NUMBER NOT NULL
);

create table JABATAN( --sudah
	ID NUMBER PRIMARY KEY, 
	NAMA_JABATAN VARCHAR2(50) NOT NULL, 
	GAJI NUMBER
);

create table KARYAWAN( --sudah 
	ID NUMBER PRIMARY KEY,
	ID_JABATAN NUMBER REFERENCES JABATAN(ID),
	USERNAME VARCHAR2(12) UNIQUE, 
	PASS VARCHAR2(50) NOT NULL,
	NAMA_KARYAWAN VARCHAR2(50) NOT NULL,
	CUTI NUMBER NOT NULL,
	TGL_MASUK DATE NOT NULL
);

create table ABSENSI(
	ID NUMBER PRIMARY KEY,
	ID_KARYAWAN NUMBER REFERENCES KARYAWAN(ID),
	JAM_HADIR DATETIME NOT NULL, 
	JAM_PULANG DATETIME NOT NULL,
	TGL_ABSEN DATE NOT NULL
);

CREATE TABLE KEHADIRAN(
	ID NUMBER PRIMARY KEY, 
	ID_KARYAWAN NUMBER REFERENCES KARYAWAN(ID),
	JADWAL_HADIR NUMBER NOT NULL
);

create table TRANSAKSI(
	ID NUMBER PRIMARY KEY,
	NOMOR_NOTA VARCHAR2(15) NOT NULL, 
	METODE_PEMBAYARAN VARCHAR2(50) NOT NULL, 
	TOTAL_PEMBELIAN NUMBER NOT NULL, 
	TGL_PEMBELIAN DATE NOT NULL 
);

create table PELANGGAN(
	ID NUMBER PRIMARY KEY,
	NAMA_PELANGGAN VARCHAR2(50) NOT NULL,
	ALAMAT VARCHAR2(50) NOT NULL,
	NO_TELP VARCHAR(12) UNIQUE
);

create table D_TRANSAKSI(
	ID_TRANSAKSI NUMBER REFERENCES TRANSAKSI(ID), 
	ID_PELANGGAN NUMBER REFERENCES PELANGGAN(ID),
	ID_MENU NUMBER REFERENCES MENU(ID),
	TGL_PEMBELIAN DATE NOT NULL
);

INSERT INTO JENIS_MAKANAN VALUES(1,'SE001','SEAFOOD');
INSERT INTO JENIS_MAKANAN VALUES(2,'AY001','AYAM');
INSERT INTO JENIS_MAKANAN VALUES(3,'SA001','SAYUR');

INSERT INTO MENU VALUES(1,1,'CG001','CUMI GORENG TEPUNG',1,35000);
INSERT INTO MENU VALUES(2,1,'CG002','CUMI GORENG MENTEGA',0,20000);
INSERT INTO MENU VALUES(3,2,'AB001','AYAM BAKAR',1,35000);
INSERT INTO MENU VALUES(4,3,'CB001','CAH BABY KAILAN',0,37000);
INSERT INTO MENU VALUES(5,3,'CK001','CAH KANGKUNG',1,21000);

INSERT INTO PELANGGAN VALUES(1,'BUDI DOREMI','JL. BUNTU 4 NO 7','087853111900');
INSERT INTO PELANGGAN VALUES(2,'MICHAEL ANGELO', 'JL. RAYA 6 NO 10','08972018528');
INSERT INTO PELANGGAN VALUES(3,'BIMA SAPUTRA','JL. NINJA 2 NO 17','08977205819');

INSERT INTO KARYAWAN VALUES(1,1,'PATKUS123','PatricKus','PATRICK KUSANAGI',4);
INSERT INTO KARYAWAN VALUES(2,3,'ANDREHEBAT','AndrianSug','ANDRIAN SUGIANTO',2);
INSERT INTO KARYAWAN VALUES(3,4,'LUKKY23','LukkyHar','LUKKY HARIYANTO',2);
INSERT INTO KARYAWAN VALUES(4,2,'STEVEN57','StevenLim','STEVEN LIEM',1);

INSERT INTO JABATAN VALUES(1,'MANAJER',5000000);
INSERT INTO JABATAN VALUES(2,'KOKI',6000000);
INSERT INTO JABATAN VALUES(3,'PELAYAN',3500000);
INSERT INTO JABATAN VALUES(4,'KASIR',4000000);

